[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "simplecanvas"
version = "0.0.1"
readme = "README.md"
dependencies = [
  "jinja2",
  "requests",
  "pyyaml",
]

[tool.black]
line-length = 80
